version: '3.6'

services:

  web:
    image: nginx:1.11.10-alpine
    depends_on:
      - app
    ports:
      - 8888:80
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./public/:/app/public/
      - ./composer.json:/app/composer.json
