version: '3.6'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./public/:/app/public/
      - ./composer.json:/app/composer.json
